# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorgany < Formula
  desc "Gorgany | Testing Things"
  homepage "https://github.com/andrii-zakurenyi/gorgany"
  version "0.1.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.8/gorgany_0.1.8_darwin_amd64.tar.gz"
      sha256 "d925c0c4854dc0d0e718c20cb816b8c00fce2c8057bc09e32adce61a6f0985b2"

      def install
        bin.install "v0.1.8/gorgany-darwin-x64"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.8/gorgany_0.1.8_darwin_arm64.tar.gz"
      sha256 "aba1d828493a9a9ab542c2e357f6faf943546ac597380b6a40e1bb1c7e2b66d5"

      def install
        bin.install "v0.1.8/gorgany-darwin-arm64"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.8/gorgany_0.1.8_linux_amd64.tar.gz"
      sha256 "8426d153f165a5653a9f527c7ddd8e5732e2590745a1823a7ddb3b527bedf2dd"

      def install
        bin.install "v0.1.8/gorgany-linux-x64"
      end
    end
  end
end
