# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorgany < Formula
  desc "Gorgany | Testing Things"
  homepage "https://github.com/andrii-zakurenyi/gorgany"
  version "0.1.19"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.19/gorgany-darwin-arm64"
      sha256 "3c013cda530f28b90a79cdb768c3ab2c2a92c39c1476909058f2aa8ba6d96f2d"

      def install
        bin.install "gorgany-darwin-arm64" => "gorgany"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.19/gorgany-darwin-x64"
      sha256 "250b0c3bf95ff44e0d32a9838eaa7447337a890993a029561660c2115497f84e"

      def install
        bin.install "gorgany-darwin-x64" => "gorgany"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.19/gorgany-linux-x64"
      sha256 "e8d72aa88b47f175bcc3d25e0068567487147e88a1f7b84e640ad2fac7a0d39a"

      def install
        bin.install "gorgany-linux-x64" => "gorgany"
      end
    end
  end
end
