# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gorgany < Formula
  desc "Gorgany | Testing Things"
  homepage "https://github.com/andrii-zakurenyi/gorgany"
  version "0.1.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.13/gorgany-darwin-x64"
      sha256 "dbefbb4d3f541d47fbb4ce0077ac81186b22f551be7f87b5dc4f041e04b8ff13"

      def install
        bin.install "gorgany"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.13/gorgany-darwin-arm64"
      sha256 "5a1d5ea2dee21b121f10cdb60e82ce866d6d815447d413b43c8d3483e1abd3cd"

      def install
        bin.install "gorgany"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/andrii-zakurenyi/gorgany/releases/download/v0.1.13/gorgany-linux-x64"
      sha256 "f9a56c02440d68e58303254d8e372a5c06f01d4710d857352443293bfc1dc79b"

      def install
        bin.install "gorgany"
      end
    end
  end
end
